on: push
name: Test File
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: test
      id: test
      uses: ./
      continue-on-error: true


    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      if: steps.test.outputs.status == 'failure'
      with:
         body: |
           Detected Trailing Spaces:
           ${{ steps.test.outputs.result }}


