on: push
name: Test File
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      id: test
      uses: ./
      continue-on-error: true

    - name: Check log
      if: steps.test.outputs.status == 'failure'
      id: log
      run: echo ::set-output name=result::$(cat test.log)


    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      if: steps.test.outputs.status == 'failure'
      with:
        body: |
          Result:
           ${{ steps.log.outputs.result }}
