on: push
name: Test File
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: tester
      id: tester
      uses: ./
      continue-on-error: true

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      if: steps.tester.outputs.status == 'failure'
      with:
        body: |
          Result:
          cat test.log
